#Synthetic Manufacturing Production Analytics Dataset

This dataset is synthetic and was created for learning and portfolio demonstration purposes. It does not represent real company data.

Files: products.csv, production.csv, downtime.csv, downtime_factors.csv.

##Library

In [ ]:
import pandas as pd
from google.colab import files

###Products File

In [ ]:
upload = files.upload()

Saving products.csv to products (1).csv

In [ ]:
products = pd.read_csv('products.csv')
products.head()

  product_id product_name   size  standard_batch_time_min
0       P001         Cola  600ml                       55
1       P002   Lemon Lime  600ml                       50
2       P003       Orange  600ml                       52
3       P004    Diet Cola  600ml                       58
4       P005         Cola     2L                       72

In [ ]:
products.shape

(5, 4)

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   product_id               5 non-null      object
 1   product_name             5 non-null      object
 2   size                     5 non-null      object
 3   standard_batch_time_min  5 non-null      int64
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

In [ ]:
products.isnull().sum()

product_id                 0
product_name               0
size                       0
standard_batch_time_min    0
dtype: int64

In [ ]:
products.duplicated().sum()

np.int64(0)

###Production File

In [ ]:
upload = files.upload()

Saving production.csv to production (1).csv

In [ ]:
production = pd.read_csv('production.csv')
production.head()

,batch_id,date,product_id,operator,shift,start_time,end_time,actual_batch_time_min,quantity_produced
0,B0001,2026-01-17,P002,OP05,Night,22:40:00,23:45:00,65,1024
1,B0002,2026-05-10,P001,OP05,Afternoon,13:40:00,14:49:00,69,1270
2,B0003,2026-04-09,P001,OP03,Afternoon,13:40:00,14:36:00,56,1279
3,B0004,2026-05-07,P005,OP03,Night,21:00:00,22:17:00,77,768
4,B0005,2026-04-09,P004,OP01,Afternoon,13:20:00,14:23:00,63,1153

In [ ]:
production.shape

(600, 9)

In [ ]:
production.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   batch_id               600 non-null    object
 1   date                   600 non-null    object
 2   product_id             600 non-null    object
 3   operator               600 non-null    object
 4   shift                  600 non-null    object
 5   start_time             600 non-null    object
 6   end_time               600 non-null    object
 7   actual_batch_time_min  600 non-null    int64
 8   quantity_produced      600 non-null    int64
dtypes: int64(2), object(7)
memory usage: 42.3+ KB

In [ ]:
production.isnull().sum()

batch_id                 0
date                     0
product_id               0
operator                 0
shift                    0
start_time               0
end_time                 0
actual_batch_time_min    0
quantity_produced        0
dtype: int64

In [ ]:
production.duplicated().sum()

np.int64(0)

###Downtime File

In [ ]:
upload = files.upload()

Saving downtime.csv to downtime (1).csv

In [ ]:
downtime = pd.read_csv('downtime.csv')
downtime.head()

  downtime_id batch_id factor_id  downtime_minutes
0      D00001    B0002       F01                23
1      D00002    B0003       F05                13
2      D00003    B0003       F01                24
3      D00004    B0004       F01                28
4      D00005    B0004       F06                17

In [ ]:
downtime.shape

(625, 4)

In [ ]:
downtime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   downtime_id       625 non-null    object
 1   batch_id          625 non-null    object
 2   factor_id         625 non-null    object
 3   downtime_minutes  625 non-null    int64
dtypes: int64(1), object(3)
memory usage: 19.7+ KB

In [ ]:
downtime.isnull().sum()

downtime_id         0
batch_id            0
factor_id           0
downtime_minutes    0
dtype: int64

In [ ]:
downtime.duplicated().sum()

np.int64(0)

###Downtime Factors File

In [ ]:
upload = files.upload()

Saving downtime_factors.csv to downtime_factors (1).csv

In [ ]:
downtime_factors = pd.read_csv('downtime_factors.csv')
downtime_factors.head()

  factor_id             factor_name     category operator_error
0       F01         Machine Failure      Machine             No
1       F02  Preventive Maintenance  Maintenance             No
2       F03       Material Shortage     Material             No
3       F04          Operator Error        Human            Yes
4       F05      Quality Inspection      Quality             No

In [ ]:
downtime_factors.shape

(8, 4)

In [ ]:
downtime_factors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   factor_id       8 non-null      object
 1   factor_name     8 non-null      object
 2   category        8 non-null      object
 3   operator_error  8 non-null      object
dtypes: object(4)
memory usage: 388.0+ bytes

In [ ]:
downtime_factors.isnull().sum()

factor_id         0
factor_name       0
category          0
operator_error    0
dtype: int64

In [ ]:
downtime_factors.duplicated().sum()

np.int64(0)

##Exploratory Data Analysis

In [ ]:
production.describe()

       actual_batch_time_min  quantity_produced
count             600.000000         600.000000
mean               65.651667        1107.713333
std                10.373991         186.570367
min                50.000000         537.000000
25%                58.000000        1044.500000
50%                64.000000        1157.000000
75%                72.000000        1235.250000
max               102.000000        1461.000000

In [ ]:
downtime.describe()

       downtime_minutes
count        625.000000
mean          17.344000
std            7.889363
min            3.000000
25%           12.000000
50%           16.000000
75%           22.000000
max           44.000000

In [ ]:
#Berapa kali setiap produk diproduksi?
production["product_id"].value_counts()

product_id
P001    154
P005    126
P002    125
P003    122
P004     73
Name: count, dtype: int64

In [ ]:
#Setiap operator menangani berapa batch?
production["operator"].value_counts()

operator
OP02    118
OP01    107
OP03    101
OP05     97
OP04     97
OP06     80
Name: count, dtype: int64

In [ ]:
#Setiap shift berapa batch yang diproduksi?
production["shift"].value_counts()

shift
Morning      264
Afternoon    231
Night        105
Name: count, dtype: int64

In [ ]:
#Faktor downtime paling sering?
downtime["factor_id"].value_counts()

factor_id
F01    118
F06     92
F03     92
F04     87
F02     71
F05     66
F08     50
F07     49
Name: count, dtype: int64

##Production Analysis

In [ ]:
#merge products + production
production_analysis = production.merge(
    products,
    on="product_id",
    how="left"
)

In [ ]:
#Time variance
production_analysis['time_variance_min'] = (
    production_analysis['actual_batch_time_min'] -
    production_analysis['standard_batch_time_min']
)

production_analysis.head()

,batch_id,date,product_id,operator,shift,start_time,end_time,actual_batch_time_min,quantity_produced,product_name,size,standard_batch_time_min,time_variance_min
0,B0001,2026-01-17,P002,OP05,Night,22:40:00,23:45:00,65,1024,Lemon Lime,600ml,50,15
1,B0002,2026-05-10,P001,OP05,Afternoon,13:40:00,14:49:00,69,1270,Cola,600ml,55,14
2,B0003,2026-04-09,P001,OP03,Afternoon,13:40:00,14:36:00,56,1279,Cola,600ml,55,1
3,B0004,2026-05-07,P005,OP03,Night,21:00:00,22:17:00,77,768,Cola,2L,72,5
4,B0005,2026-04-09,P004,OP01,Afternoon,13:20:00,14:23:00,63,1153,Diet Cola,600ml,58,5

In [ ]:
production_analysis['time_variance_min'].describe()

count    600.000000
mean       8.368333
std        6.327933
min        0.000000
25%        3.000000
50%        8.000000
75%       13.000000
max       30.000000
Name: time_variance_min, dtype: float64

In [ ]:
#Rata-rata produk yang memiliki waktu lebih lama dibandingkan standar produksinya
production_analysis.groupby('product_id')['time_variance_min'].mean()

product_id
P001    8.103896
P002    7.960000
P003    8.729508
P004    8.150685
P005    8.873016
Name: time_variance_min, dtype: float64

In [ ]:
#Batch dengan downtime lebih lama memiliki time variance lebih tinggi)
downtime_per_batch = downtime.groupby("batch_id")["downtime_minutes"].sum().reset_index()

downtime_per_batch.head()

  batch_id  downtime_minutes
0    B0002                23
1    B0003                37
2    B0004                89
3    B0005                27
4    B0006                17

In [ ]:
production_analysis = production_analysis.merge(
    downtime_per_batch,
    on="batch_id",
    how="left"
)

production_analysis.head()

,batch_id,date,product_id,operator,shift,start_time,end_time,actual_batch_time_min,quantity_produced,product_name,size,standard_batch_time_min,time_variance_min,downtime_minutes
0,B0001,2026-01-17,P002,OP05,Night,22:40:00,23:45:00,65,1024,Lemon Lime,600ml,50,15,NaN
1,B0002,2026-05-10,P001,OP05,Afternoon,13:40:00,14:49:00,69,1270,Cola,600ml,55,14,23.0
2,B0003,2026-04-09,P001,OP03,Afternoon,13:40:00,14:36:00,56,1279,Cola,600ml,55,1,37.0
3,B0004,2026-05-07,P005,OP03,Night,21:00:00,22:17:00,77,768,Cola,2L,72,5,89.0
4,B0005,2026-04-09,P004,OP01,Afternoon,13:20:00,14:23:00,63,1153,Diet Cola,600ml,58,5,27.0

In [ ]:
production_analysis["downtime_minutes"].isnull().sum()

np.int64(165)

In [ ]:
#Ubah NaN jadi 0
production_analysis["downtime_minutes"] = (
    production_analysis["downtime_minutes"].fillna(0)
)

In [ ]:
production_analysis["downtime_minutes"].isnull().sum()

np.int64(0)

In [ ]:
production_analysis["downtime_status"] = production_analysis["downtime_minutes"].apply(
    lambda x: "Has Downtime" if x > 0 else "No Downtime"
)

In [ ]:
production_analysis.groupby("downtime_status")["time_variance_min"].mean()

downtime_status
Has Downtime    9.096552
No Downtime     6.448485
Name: time_variance_min, dtype: float64

In [ ]:
production_analysis[
    ["downtime_minutes", "time_variance_min"]
].corr()

                   downtime_minutes  time_variance_min
downtime_minutes           1.000000           0.073497
time_variance_min          0.073497           1.000000